### ISSUE TITLE
Resolve authentication issue using stored credentials.

### ISSUE THREAD

**Issue by bradwbonn** [bradwbonn/rsync-checkpoint#13]
It seems there's no way to connect without storing an explicit user/password pair somewhere.
Asking if that's true or if there's an alternative to maybe use base64 at least (like I'm trying now) or how best to use the API key generator.

**Comment by bradwbonn** [comment]
https://github.com/cloudant/python-cloudant/issues/49
An open question at this point.  I'd rather not store user/password combinations anywhere in their raw form.

**Comment by alfinkel** [comment]
See https://github.com/cloudant/python-cloudant/issues/49#issuecomment-164533706

**Comment by bradwbonn** [comment]
Currently the Cloudant library doesn't natively support the auth token model.  I'm going to try to extend it for the time being until this is added.  It does mean removal of all context manager use of the Cloudant library, however.

**Comment by alfinkel** [comment]
@bradwbonn:  I had a bit more time to think about it.  You should be able to create your own context manager much in the same way I detailed circumventing the `connect()` method.  See https://github.com/cloudant/python-cloudant/issues/49#issuecomment-164551190.  Let me know if you want some more detail and I'd be happy to provide it.

**Comment by bradwbonn** [comment]
Thanks alfinkel,
I may do so at a later date once the first implementation of this tool gets complete.  For now, I think I'll store the user/pass credentials and use the native context manager to get things rolling, and examine an auth header as possible future "enhancement."

**Comment by bradwbonn** [comment]
the base64 doesn't significantly improve any security measures aside from over-the-shoulder.  For now, using username/password combination locally stored.
